---
- name: Update and Upgrade APT Packages
  hosts: all
  become: yes
  tasks:
    - name: Update APT package index
      apt:
        update_cache: yes

    - name: Upgrade all APT packages
      apt:
        upgrade: dist
        autoremove: yes
        autoclean: yes

