all:
  children:
    ControlPlane:
      hosts:
        Ewnix_1_CP:
          ansible_host: 157.245.84.29

    WorkerNodes:
      hosts:
        Ewnix_1_WN1:
          ansible_host: 64.227.6.139
        Ewnix_1_WN2:
          ansible_host: 159.223.96.174
