---
- name: Install/Update K3s on Control Plane
  shell: |
    curl -sfL https://get.k3s.io | sh -s - server \
    --write-kubeconfig-mode 644
  when: "'ControlPlane' in group_names"
  notify:
    - Restart K3s on Control Plane

- name: Install/Update K3s on Worker Nodes
  shell: |
    curl -sfL https://get.k3s.io | sh -s - agent \
    --server https://{{ hostvars[groups['ControlPlane'][0]].ansible_host }}:6443 \
    --token {{ k3s_token }}
  when: "'WorkerNodes' in group_names"
  notify:
    - Restart K3s on Worker Nodes
